DROP TABLE IF EXISTS SESSION_DATA;

CREATE TABLE SESSION_DATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_DATA INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE
);

INSERT INTO SESSION_DATA (ID, USER_DATA, START_DATE) VALUES (1, 1, '2021-12-15');
INSERT INTO SESSION_DATA (ID, USER_DATA, START_DATE, END_DATE) VALUES (2, 1, '2021-12-15', '2021-12-21');
INSERT INTO SESSION_DATA (ID, USER_DATA, START_DATE, END_DATE) VALUES (3, 2, '2021-12-15', '2021-12-27');